```{r questions, echo = FALSE, results = "hide"}
# questions/answers
questions1 <- character(5)
solutions1 <- logical(5)
explanations1 <- character(5)
questions1[1] <- "La probabilité qu'il pleuve lundi."
questions1[2] <- "La probabilité qu'il pleuve, sachant qu'on est lundi."
questions1[3] <- "La probabilité qu'on soit lundi, sachant qu'il pleut."
questions1[4] <- "La probabilité qu'on soit lundi et qu'il pleuve."
questions1[5] <- "La probabilité qu'il pleuve et qu'on soit lundi."
solutions1[1] <- FALSE
solutions1[2] <- FALSE
solutions1[3] <- TRUE
solutions1[4] <- FALSE
solutions1[5] <- FALSE
explanations1[1] <- "Ceci correspond à Pr(pluie,lundi)."
explanations1[2] <- "Ceci correspond à Pr(pluie|lundi)."
explanations1[4] <- "Ceci correspond à Pr(lundi,pluie), équivalent à Pr(pluie,lundi)."
explanations1[5] <- "Ceci correspond à Pr(pluie,lundi), équivalent à Pr(lundi,pluie)."
```

Question
========

```{r, echo = FALSE}
pts <- 1
pts_string <- if (exams::match_exams_call() == "exams2pdf") {
  sprintf("\\emph{(%s point%s)} ", pts, if (pts > 1) "s" else "")
} else {
  ""
}
```

`r pts_string`Choisissez l'affirmation ou les affirmations correspondant à l'expression : $\Pr(\text{lundi}|\text{pluie})$.

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions1, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions1, "True", "False"), explanations1, markup = "markdown")
```

Meta-information
================
exname: cond_prob
extype: mchoice
exsolution: `r mchoice2string(solutions)`
expoints: 1
