```{r questions, echo = FALSE, results = "hide"}
# questions/answers
questions2 <- character(5)
solutions2 <- logical(5)
questions2[1] <- "La première ligne décrit les priors, la deuxième ligne la fonction de vraisemblance, et les lignes suivantes le posterior."
questions2[2] <- "La première ligne décrit la fonction de vraisemblance, la deuxième ligne le modèle linéaire, et les lignes suivantes les priors."
questions2[3] <- "La première ligne décrit le modèle linéaire, la deuxième ligne la fonction de vraisemblance, et les lignes suivantes les priors."
questions2[4] <- "Les deux premières lignes décrivent le modèle linéaire, et les lignes suivantes les priors."
questions2[5] <- "Les deux premières lignes décrivent le modèle linéaire, et les lignes suivantes le posterior."
solutions2[1] <- FALSE
solutions2[2] <- TRUE
solutions2[3] <- FALSE
solutions2[4] <- FALSE
solutions2[5] <- FALSE
```

Question
========

```{r, echo = FALSE}
pts <- 2
pts_string <- if (exams::match_exams_call() == "exams2pdf") {
  sprintf("\\emph{(%s point%s)} ", pts, if (pts > 1) "s" else "")
} else {
  ""
}
```

`r pts_string`Dans le modèle ci-dessous,

$$
\begin{aligned}
y_{i} & \sim \mathrm{Normal}(\mu, \sigma) \\
\mu_i & = \alpha + \beta \cdot x_{i} \\
\alpha & \sim \mathrm{Normal}(0,10) \\
\beta & \sim \mathrm{Normal}(0,1) \\
\sigma & \sim \mathrm{Exponential}(2)
\end{aligned}
$$

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions2, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions2, "True", "False"), markup = "markdown")
```

...

Meta-information
================
exname: Linear model
extype: schoice
exsolution: `r mchoice2string(solutions)`
expoints: 2
